# Generated by Django 4.1.4 on 2023-03-31 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RegusterForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("age", models.IntegerField()),
                ("address", models.CharField(max_length=100)),
                ("contact", models.IntegerField()),
                ("mail", models.EmailField(max_length=50)),
            ],
            options={
                "db_table": "datas",
            },
        ),
    ]
